- name: "include_vars {{ item }}"
  include_vars: "{{ item }}.yml"

- name: show dictionary
  shell: ssh bprokin@"{{item.ips[0]}}" hostname -a |awk '{print $1}'
  with_items: "{{ dbs }}"
  register: hostname_lists


- name: "Make jenkins file"
  template:
    src   : "jenkinsfile.j2"
    dest  : "/Users/bprokin/wp/tmp/jenkinsfile_{{ item }}"
    mode  : 0664
    force : true

