import groovy.json.JsonBuilder
import groovy.json.JsonSlurper

pipeline{
    agent {
        docker { 
            image 'stcit_docker/ansible:21'
            registryUrl 'https://nexus.fbsvc.bz'
            registryCredentialsId '446beb45-cee2-41b4-b67d-57df7598ed31'
            label 'build'
            args "-u root"
        }
    }
    options {
        timeout(time: 3, unit: 'DAYS') 
    }

    stages {
        stage('git pull') {
            steps {
                git branch: 'master', 
                    credentialsId: '39c35701-7360-44a1-829d-d789133bd14f', 
                    url: 'git@gitlab.fbsvc.bz:itdev/bobber-lite.git'
            }
        }
        stage('CF config') {
            steps{
                script {
                    withCredentials([
//                        usernamePassword(credentialsId: 'cloudflare_global_mirrors', usernameVariable: 'cf_account_id', passwordVariable: 'cf_token'),
//usernamePassword(credentialsId: 'gandi_global_mirrors', usernameVariable: 'gandi_org_id', passwordVariable: 'gandi_token')
                        ]) {
                        def lines = sh (returnStdout: true, script: """echo '{"stage": "configure_CF", "dry_run": "${dry_run}", "domain": "${domain}",  "bobber_url": "${bobber_url}", "bobber_token": "${bobber_token}", "cf_account_id": "${cf_account_id}", "cf_token": "${cf_token}", "gandi_token": "${gandi_token}", "gandi_org_id": "${gandi_org_id}", "gandi_owner": ${gandi_owner}, "action_id": "${action_id}", "action_token": "${action_token}"}' | src/bobber_actions/actions/buy_domain_staging.py""" ).trim().readLines()
                        env.cf_configured_data=lines.get(lines.size()-1).replaceAll("\'", "\"")
                        println(cf_configured_data)
                    }
                }
            }
        }
        stage('Gandi - buy domain') {
            steps{
                withCredentials([
//                        usernamePassword(credentialsId: 'cloudflare_global_mirrors', usernameVariable: 'cf_account_id', passwordVariable: 'cf_token'),
//                        usernamePassword(credentialsId: 'gandi_global_mirrors', usernameVariable: 'gandi_org_id', passwordVariable: 'gandi_token')
                        ]) {
                    sh"""
                    echo '{"stage": "buy_domain", "cf_configured_data":${env:cf_configured_data},  "dry_run": "${dry_run}", "domain": "${domain}",  "bobber_url": "${bobber_url}", "bobber_token": "${bobber_token}", "cf_account_id": "${cf_account_id}", "cf_token": "${cf_token}", "gandi_token": "${gandi_token}", "gandi_org_id": "${gandi_org_id}", "gandi_owner": ${gandi_owner}, "action_id": "${action_id}", "action_token": "${action_token}"}' | src/bobber_actions/actions/buy_domain_staging.py
                    """
                }
            }
        }
        stage('Bobber set status buy_done') {
            steps{
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    withCredentials([
    //                        usernamePassword(credentialsId: 'cloudflare_global_mirrors', usernameVariable: 'cf_account_id', passwordVariable: 'cf_token'),
//                            usernamePassword(credentialsId: 'gandi_global_mirrors', usernameVariable: 'gandi_org_id', passwordVariable: 'gandi_token')
                            ]) {
                        sh"""
                        echo '{"stage": "set_domain_status_buy_done", "cf_configured_data":${env:cf_configured_data},  "dry_run": "${dry_run}", "domain": "${domain}",  "bobber_url": "${bobber_url}", "bobber_token": "${bobber_token}", "cf_account_id": "${cf_account_id}", "cf_token": "${cf_token}", "gandi_token": "${gandi_token}", "gandi_org_id": "${gandi_org_id}", "gandi_owner": ${gandi_owner}, "action_id": "${action_id}", "action_token": "${action_token}"}' | src/bobber_actions/actions/buy_domain_staging.py
                        """
                    }
                }
            }
        }
        stage('CF check status') {
            steps{
                withCredentials([
//                        usernamePassword(credentialsId: 'cloudflare_global_mirrors', usernameVariable: 'cf_account_id', passwordVariable: 'cf_token'),
//                        usernamePassword(credentialsId: 'gandi_global_mirrors', usernameVariable: 'gandi_org_id', passwordVariable: 'gandi_token')
                        ]) {
                    sh"""
                    echo '{"stage": "activate_domain", "cf_configured_data":${env:cf_configured_data}, "dry_run": "${dry_run}", "domain": "${domain}",  "bobber_url": "${bobber_url}", "bobber_token": "${bobber_token}", "cf_account_id": "${cf_account_id}", "cf_token": "${cf_token}", "gandi_token": "${gandi_token}", "gandi_org_id": "${gandi_org_id}", "gandi_owner": ${gandi_owner}, "action_id": "${action_id}", "action_token": "${action_token}"}' | src/bobber_actions/actions/buy_domain_staging.py
                    """
                }
            }
        }
    }
}