---
- shell: "python --version|awk '{print $2}'"
  register: python_installed

- name: Check contents for emptiness
  ansible.builtin.debug:
    msg: "{{ python_installed.stdout }} and {{ python_release }}"
    
- include_tasks: update_packages.yml
  when:
    - python_installed.stdout != python_release
- include_tasks: reboot.yml
  when:
    - python_installed.stdout != python_release
- include_tasks: debian12.yml
  when:
    - python_installed.stdout != python_release
- include_tasks: make.yml
  when:
    - python_installed.stdout != python_release
- include_tasks: install.yml
  when:
    - python_installed.stdout != python_release