---
- name: Get an issue
  community.general.jira:
    uri: '{{ server }}'
    username: '{{ user }}'
    password: '{{ pass }}'
    project: STCIT
    operation: fetch
    issue: STCIT-43236
  register: issue

- name: "Make wars file"
  template:
    src   : "new_wars.j2"
    dest  : "/Users/bprokin/wp/tmp/new_wars"
    mode  : 0664
    force : true
