---

python_release: 3.12.4 # See https://www.python.org/downloads/source/
python_src_dir: /tmp
python_archive: Python-{{ python_release }}.tgz
python_url: "https://nexus.fbsvc.bz/repository/robot_raw_models/python/{{ python_archive }}"
robot_raw_models:
  username: bprokin 
  password: a9VvCNt0jZHxeKzzMy9z4JGTCPdLPtUP
packages:
  - d12:
    - git
    - gcc
    - make
    - tar
    - vim
    - wget
    - libncursesw5-dev
    - libssl-dev
    - libsqlite3-dev
    - tk-dev
    - libgdbm-dev
    - libc6-dev
    - libbz2-dev
    - libffi-dev
    - zlib1g-dev
    - build-essential
    - liblzma-dev
    - tcl-dev
