---
- name: Install Conda
  block:
    - name: Download anaconda
      get_url:
        url: "{{ anaconda_url }}"
        dest: /srv/{{ anaconda_bin }}
        checksum: md5:a590547c03068e1cb3ca731788f48442
        username: "{{ robot_raw_models.username }}"
        password: "{{ robot_raw_models.password }}"
        mode: 0550
        timeout : 200
      register: get_url_result
      retries: 300
      delay: 10
      until: get_url_result.checksum_src == get_url_result.checksum_dest

    - name: Create conda folder
      become: True
      file:
        path: /srv/anaconda3
        state: directory
        mode: 755
        recurse: yes

    - name: Run the installer
      shell: /srv/{{ anaconda_bin }} -b -u -p /srv/anaconda3

    - name: Remove the installer
      file:
        state: absent
        path: /srv/{{ anaconda_bin }}

    - name: conda - read permission for all
      become: True
      file:
        path: /srv/anaconda3
        mode: +r
        recurse: yes

    - name: conda - execution permission for all
      become: True
      file:
        path: /srv/anaconda3/bin
        mode: +x
        recurse: yes