---
- include_tasks: update_packages.yml
- name: Check contents for emptiness
  ansible.builtin.debug:
    msg: "{{ ansible_distribution_major_version }} and "
    
- include_tasks: debian12.yml
  when:
    - ansible_distribution_major_version == "11"
- include_tasks: debian11.yml
  when:
    - ansible_distribution_major_version == 10
