---
- name: Upgrade OS packages
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: yes

- name: Remove dependencies that are no longer required.
  ansible.builtin.apt:
    autoremove: yes
- name: Remove useless packages from the cache
  ansible.builtin.apt:
    autoclean: yes