- hosts: localhost
  gather_facts: no

  vars:
    domains: [${domainsQuoted}]

  tasks:
  - name: Create private key (RSA, 4096 bits)
    community.crypto.openssl_privatekey:
      path: certificate.key
      size: 2048

  - name: Create certificate signing request (CSR) for self-signed certificate
    community.crypto.openssl_csr:
      privatekey_path: certificate.key
      common_name: "{{ domains[0] }}"
      organization_name: Ansible, Inc.
      subject_alt_name: "{{ [ 'DNS:' ] | product(domains[1:]) | map('join') | list }}"
    register: csr


  - name: Sign the CSR with CA
    community.crypto.openssl_certificate:
      path: certificate.pem
      csr_content: "{{ csr.csr }}"
      privatekey_path: certificate.key
      cacert_path: ca.crt
      provider: selfsigned
      days: 36500


  - name: Get certificate information
    community.crypto.x509_certificate_info:
      path: certificate.pem
    register: result

  - name: Show certificate information
    debug:
       msg: "{{ result }}"