- hosts: localhost
  gather_facts: yes

  vars:
    dbs:
      - ips:
        - "10.209.111.101"
        - "10.209.111.102"
        - "10.254.9.101/23"
      - ips:
        - "10.209.111.69"
        - "10.209.111.70"
        - "10.254.9.69/23"
      - ips:
        - "10.209.111.91"
        - "10.209.111.92"
        - "10.254.9.91/23"
      - ips:
        - "10.209.111.137"
        - "10.209.111.138"
        - "10.254.9.137/23"
      - ips:
        - "10.209.111.120"
        - "10.209.111.128"
        - "10.254.9.120/23"
      - ips:
        - "10.209.111.107"
        - "10.209.111.108"
        - "10.254.9.107/23"
      - ips:
        - "10.209.111.57"
        - "10.209.111.58"
        - "10.254.9.57/23"
      - ips:
        - "10.209.111.10"
        - "10.209.111.11"
        - "10.254.9.10/23"

  tasks:
  - name: show dictionary
    shell: ssh bprokin@"{{item.ips[0]}}" hostname -a
    register: hostname_list
    with_items: "{{ dbs }}"



  - name: show dictionary
    debug:
      var: hostname_list
